### ISSUE TITLE
Math in docstrings

### ISSUE THREAD

**Issue by DomagojHack** [mitmproxy/pdoc#225]
Maybe I am missing something. Is there a way to make pdoc render tex math formulas? My docstrings contain a lot of them. 

Formulas like this:

`$\frac{x}{1}`

Cheers

**Comment by mhils** [comment]
There is! I have just pushed an example to [examples/math](https://github.com/mitmproxy/pdoc/tree/main/examples/math), does that do what you were looking for? 😃

**Comment by DomagojHack** [comment]
Yes, thanks for the example. Formulas are now stylized like LaTeX math, however I am getting another issue (maybe not pdoc related). My fractions are not rendered properly.

for 
```$$\frac{w}{10} + i*day$$```

I am getting

![2021-02-18_16-16](https://user-images.githubusercontent.com/2804094/108378123-03dab580-7205-11eb-898a-2d6a05b71085.png)

instead of:

![2021-02-18_16-20](https://user-images.githubusercontent.com/2804094/108378674-82cfee00-7205-11eb-810a-4084ff7d7e01.png)

**Comment by mhils** [comment]
Good catch, that can be confusing here. I've added an explanation to https://pdoc.dev/docs/math/math_demo.html 😃

**Comment by abubelinha** [comment]
@mhils I saw the explanation but I still cannot see formulas being rendered (same problem [described above](https://github.com/mitmproxy/pdoc/issues/225#issuecomment-781419824)).

The math.html.jinja2 file linked there says "_MathJax by default does not define $ as a math delimiter because it's commonly used in non-mathematical settings. **We add it here**_."
Not sure if I understood correctly: that template is or is not already being used by default? 
It is located in my `pdoc/templates` folder, but not in `pdoc/templates/default`. Should I move it there to activate it?

Currently,  when using `$$dist = \\sqrt { a^2+b^2 }$$` I just see **$$dist = \\sqrt { a^2+b^2 }$$** (the square root symbol is not being displayed, and $$ symbols are visible in resulting html documentation)

**Comment by mhils** [comment]
@abubelinha: This issue predates the current builtin implementation. You need to run `pdoc --math ...` to include MathJax and render formulas. Are you doing that?

> Not sure if I understood correctly: that template is or is not already being used by default?

`math.html.jinja2` is used by default if `--math` is passed.

**Comment by abubelinha** [comment]
Ah ... I see.
I am using pdoc as a library (#325), not from command line.
How do I pass `--math` in that case?

**Comment by mhils** [comment]
See https://pdoc.dev/docs/pdoc.html#configuring-pdoc (and then https://pdoc.dev/docs/pdoc/render.html#configure). :)

**Comment by abubelinha** [comment]
So the answer (for my own record) is:

```Python
import pdoc
pdoc.render.configure(math=True)
pdoc.pdoc( ... whatever ...)
```
Thanks a lot !!
